default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: rootinfoway
  host: localhost

development:
  <<: *default
  database: apilinode_development

test:
  <<: *default
  database: apilinode_test

production:
  <<: *default
  database: apilinode_production
